Basic Python - Assignment 1 - START

In [ ]:
# Soal 1
a = input ("Nama: ")
b = input ("Umur: ")
c = input ("Tinggi: ")
print ("Nama saya", a, ", umur saya", b,  "tahun dan tinggi saya", c, "cm.") 

Nama: Ben Van Lier
Umur: 36
Tinggi: 191.5
Nama saya Ben Van Lier , umur saya 36 tahun dan tinggi saya 191.5 cm.


In [ ]:
# Soal 2
a = 22/7
b = float (input ("jari-jari lingkaran: "))
c = a*(b**2)
print ("Luas lingkaran dengan jari-jari", b, "cm adalah", c, "cm kuadrat.")
# pembuatan kuadrat gagal

jari-jari lingkaran: 2
Luas lingkaran dengan jari-jari 2.0 cm adalah 12.571428571428571 cm kuadrat.


In [ ]:
# Soal 2 - kuadrat???
a = 22/7
b = float (input ("jari-jari lingkaran: "))
c = a*(b**2)
d = print ("\u00b2")
print (d)
print ("Luas lingkaran dengan jari-jari", b, "cm adalah", c, "cm", d, ".")

jari-jari lingkaran: 2
²
None
Luas lingkaran dengan jari-jari 2.0 cm adalah 12.571428571428571 cm None .


In [ ]:
# Soal 3 (a) - berhasil
nilaiteori = float (input("Nilai Ujian Teori :"))
nilaipraktek = float (input("Nilai Ujian Praktek :"))
if nilaiteori >= 70 and nilaipraktek >= 70:
  print ("Selamat, anda lulus!")
elif nilaiteori <= 70 and nilaipraktek < 70:
  print ("Anda harus mengulang ujian praktek.")
elif nilaiteori < 70 and nilaipraktek<= 70:
  print ("Anda harus mengulang ujian teori.")
else:
  nilaiteori <= 70 and nilaipraktek <= 70
  print ("Anda harus mengulang ujian teori dan praktek.")

Nilai Ujian Teori :82.5
Nilai Ujian Praktek :73.2
Selamat, anda lulus!


In [ ]:
# Soal 3 (b) - gagal???
nilaiteori = float (input("Nilai Ujian Teori :"))
nilaipraktek = float (input("Nilai Ujian Praktek :"))
if nilaiteori >= 70 and nilaipraktek >= 70:
  print ("Selamat, anda lulus!")
elif nilaiteori <= 70 and nilaipraktek < 70:
  print ("Anda harus mengulang ujian praktek.")
elif nilaiteori < 70 and nilaipraktek<= 70:
  print ("Anda harus mengulang ujian teori.")
else:
  nilaiteori <= 70 and nilaipraktek <= 70
  print ("Anda harus mengulang ujian teori dan praktek.")

Nilai Ujian Teori :65.75
Nilai Ujian Praktek :72.45
Anda harus mengulang ujian teori dan praktek.


In [ ]:
# Soal bonus piramida
for i in range (0,3):
  for j in range (0,3):
    if j>i:
      print()
      break
    else:
      print("*", end = "")


*
**
***

In [ ]:
# Soal bonus - while - GAGAL????
jumlahbaris = 5
baris = 0
bintang = 0
while baris < jumlahbaris:
  if(bintang) >= (baris+1):
    print()
    baris = baris+1
    bintang = 0
  print ("*", end = "")
  bintang = bintang+1


*
**
***
****
*****
*

In [ ]:
# Soal bonus piramida -- BINGUNG ???
a = input ("Ketinggian piramida adalah: ")
for i in range (0, 3):
  for j in range (0, 3):
    if j>i:
      print()
      break
    else:
      print("*", end = "")

Ketinggian piramida adalah: 3
*
**
***

Basic Python - Assignment 1 - FINISH

In [ ]:
nama = "Ben Van Lier"
umur = 36
tinggi = 191.5
print ("Nama saya %s , umur saya %d tahun dan tinggi saya %f cm." % (nama, umur, tinggi))

Nama saya Ben Van Lier , umur saya 36 tahun dan tinggi saya 191.500000 cm.


In [ ]:
for i in range (0,6):
  for j in range (0,6-i):
    print ("*", end = "")
  print ()

******
*****
****
***
**
*


In [ ]:
for i in range (0,3):
  for j in range (0,3):
    if j>i:
      print()
      break
    else:
      print ("*", end = "")

*
**
***

In [ ]:
# ketinggian piramida 3
jumlahbaris = 3
baris = 0
bintang = 0
while baris < jumlahbaris:
  if (bintang) >= (baris+1):
    print()
    baris = baris+1
    bintang = 0
  print ("*", end = "")
  bintang = bintang+1

*
**
***
*

In [ ]:
nilai = int(input("Masukkan nilai tugas Anda:"))
if nilai >80:
  print("Selamat! Anda mendapat nilai A")
  print ("Pertahankan!")
elif nilai >70:
  print ("Hore! Anda mendapat nilai B")
  print ("Tingkatkan!")
elif nilai >60:
  print ("Hmmm... Anda mendapat nilai C")
  print ("Ayo semangat!")
else:
  print ("Waduh, Anda mendapat nilai D")
  print ("Yuk belajar lebih giat lagi!")

Masukkan nilai tugas Anda:89
Selamat! Anda mendapat nilai A
Pertahankan!


In [ ]:
nilaiteori = float (input("Nilai Ujian Teori :"))
nilaipraktek = float (input("Nilai Ujian Praktek :"))
if nilaiteori >= 70 and nilaipraktek >= 70:
  print ("Selamat, anda lulus!")
elif nilaiteori <= 70 and nilaipraktek < 70:
  print ("Anda harus mengulang ujian praktek.")
elif nilaiteori < 70 and nilaipraktek<= 70:
  print ("Anda harus mengulang ujian teori.")
else:
  nilaiteori <= 70 and nilaipraktek <= 70
  print ("Anda harus mengulang ujian teori dan praktek.")

Nilai Ujian Teori :67.5
Nilai Ujian Praktek :45.3
Anda harus mengulang ujian praktek.


In [ ]:
nilaiteori = float (input("Nilai Ujian Teori :"))
nilaipraktek = float (input("Nilai Ujian Praktek :"))
if nilaiteori >= 70 and nilaipraktek >= 70:
  print ("Selamat, anda lulus!")
elif nilaiteori <= 70 and nilaipraktek < 70:
  print ("Anda harus mengulang ujian praktek.")
elif nilaiteori < 70 and nilaipraktek<= 70:
  print ("Anda harus mengulang ujian teori.")
else:
  nilaiteori <= 70 and nilaipraktek <= 70
  print ("Anda harus mengulang ujian teori dan praktek.")

Nilai Ujian Teori :65.6
Nilai Ujian Praktek :72.3
Anda harus mengulang ujian teori dan praktek.


In [ ]:
nilaiteori = float (input("Nilai Ujian Teori :"))
nilaipraktek = float (input("Nilai Ujian Praktek :"))
if nilaiteori >= 70 and nilaipraktek >= 70:
  print ("Selamat, anda lulus!")
elif nilaiteori <= 70 and nilaipraktek < 70:
  print ("Anda harus mengulang ujian praktek.")
elif nilaiteori < 70 and nilaipraktek<= 70:
  print ("Anda harus mengulang ujian teori.")
else:
  nilaiteori <= 70 and nilaipraktek <= 70
  print ("Anda harus mengulang ujian teori dan praktek.")

Nilai Ujian Teori :55.4
Nilai Ujian Praktek :45.3
Anda harus mengulang ujian praktek.


In [ ]:
# program menghitung luas lingkaran
phi = 22/7
r = jari-jarilingkaran
luas lingkaran = phi*r^2

SyntaxError: ignored

In [ ]:
nama = "Ben Van Lier"
umur = 36
tinggi = 191.5
print ("Nama saya %s , umur saya %d tahun dan tinggi saya %f cm." % (nama, umur, tinggi))

Nama saya Ben Van Lier , umur saya 36 tahun dan tinggi saya 191.500000 cm.


In [ ]:
nilai = input ('Masukkan angka:')

Masukkan angka:90


In [ ]:
Nama = "Ben Van Lier"
Umur = 36
Tinggi = 191.5
input ("Nama saya:")
input ("Umur saya:")
input ("Tinggi saya:")


Nama saya:Gema
Umur saya:24
Tinggi saya:175


'175'

In [ ]:
import numpy as np
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
ones = np.ones ((5,5))
two = np.full ((3,3), 2)
ones [1:-1, 1:-1] = two
ones [0:5, 2] = 3
print (ones)

[[1. 1. 3. 1. 1.]
 [1. 2. 3. 2. 1.]
 [1. 2. 3. 2. 1.]
 [1. 2. 3. 2. 1.]
 [1. 1. 3. 1. 1.]]


In [ ]:
ones = np.ones ((5,5))
two = np.full ((3,3), 2)
ones [1:-1, 1:-1] = two
ones [0:5, 2] = 3
print (ones)

[[1. 1. 3. 1. 1.]
 [1. 2. 3. 2. 1.]
 [1. 2. 3. 2. 1.]
 [1. 2. 3. 2. 1.]
 [1. 1. 3. 1. 1.]]


In [ ]:
np.zeros((8,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((8,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
nama = "Dicoding"
umur = 5
print ("Umur %s adalah %d tahun." % (nama, umur))

Umur Dicoding adalah 5 tahun.
